package com.stulsoft.pswing;

import javax.swing.*;
import java.awt.*;

public class FlowForm {
    private JPanel mainPanel;
    private JTextField textField;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("Enter text:");
        mainPanel.add(label1);
        textField = new JTextField();
        textField.setHorizontalAlignment(4);
        textField.setText("dfddgfdfgdgf");
        mainPanel.add(textField);
        label1.setLabelFor(textField);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
